# Generated by Django 3.0.3 on 2020-06-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuereport',
            old_name='file_field',
            new_name='image_field',
        ),
    ]
