# Generated by Django 3.0.3 on 2020-06-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200601_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuereport',
            name='image_field',
        ),
    ]
