# Generated by Django 3.0.3 on 2020-06-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('image_file', models.FileField(null=True, upload_to='images')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
        ),
    ]
